### ISSUE TITLE
Could not find gem 'andand (>= 0) (>= 0) ruby', which is required by gem 'ribeye (>= 0) ruby', in any of the sources.

### ISSUE THREAD

**Issue by christiangenco** [mcmire/time_tracker#2]
Occurs when installing time_tracker

```
~/time_tracker[master*]% bundle install --without test
Fetching git://github.com/mcmire/ribeye
remote: Counting objects: 420, done.
remote: Compressing objects: 100% (171/171), done.
remote: Total 420 (delta 234), reused 420 (delta 234)
Receiving objects: 100% (420/420), 67.37 KiB | 43 KiB/s, done.
Resolving deltas: 100% (234/234), done.
Fetching source index for http://rubygems.org/
Could not find gem 'andand (>= 0) (>= 0) ruby', which is required by gem 'ribeye (>= 0) ruby', in any of the sources.
```

**Comment by mcmire** [comment]
Ugh, sorry about that. There were several issues here: 
1. The gem dependencies needed to be frozen to a year and a half ago, as none of them were frozen at all
2. I had ribeye pointing to a local version on my computer
3. The ribeye dependencies were broken (needed to point Gemfile to gemspec, not the other way around)

Give it another shot, should work now.

**Comment by christiangenco** [comment]
```
~/Desktop/time_tracker[master*]% bundle
Updating git://github.com/mcmire/ribeye
Fetching source index for http://rubygems.org/
Using rake (0.8.7) 
Installing multi_json (1.3.4) 
Installing activesupport (3.1.4) 
Installing addressable (2.2.8) 
Installing andand (1.3.1) 
...
```

Looks like your fixed andand, however...

```
...
Installing bson (1.6.2) 
Installing bson_ext (1.1.5) with native extensions 
Installing celerity (0.9.2) 
Installing culerity (0.2.15) 
Using mime-types (1.18) 
Using nokogiri (1.5.2) 
Using rack (1.4.1) 
Using rack-test (0.6.1) 
Using ffi (1.0.11) 
Installing childprocess (0.3.2) 
Installing libwebsocket (0.1.3) 
Installing rubyzip (0.9.8) 
Installing selenium-webdriver (2.21.2) 
Using xpath (0.1.4) 
Installing capybara (0.4.1.2) 
Installing stackdeck (0.2.0) 
Installing johnson (2.0.0.pre3) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
...
An error occured while installing johnson (2.0.0.pre3), and Bundler cannot continue.
Make sure that `gem install johnson -v '2.0.0.pre3'` succeeds before bundling.
```

Before I try to hunt this down, why so many gem dependencies? I can't imagine how you're using half of these in what is essentially a log file.

**Comment by mcmire** [comment]
Try using Ruby 1.8. TimeTracker doesn't work on Ruby 1.9, because Johnson doesn't work on 1.9.

You're right, I don't use all of those dependencies -- most of them are coming from my ribeye gem which was originally designed as an improved version of Steak. So it has a lot of web related stuff in there -- rack-test, capybara, etc. But I also wanted a Steak for CLI apps too. So I went ahead and added that to ribeye to save some time, but yeah it obviously doesn't make sense.

Now that 1) Steak is no longer its own thing and is a part of Capybara and 2) I've abandoned ribeye, I need to split that stuff into a separate gem.

**Comment by mcmire** [comment]
Actually, try running `bundle install --without test`. (I notice you did that the first time, but not the second time.) This will exclude ribeye and johnson and all that. That stuff's just for tests. (Although half of it _isn't_ being used.)

**Comment by christiangenco** [comment]
Ahh good catch! `bundle install --without test` worked (even on 1.9 - skipped Johnson?).

**Comment by mcmire** [comment]
Yeah, Johnson is a dependency of capybara-envjs, which is being required by ribeye.

P.S. let me know if you run into any more issues!
